package com.urbanlogiq.traveltimeexample.fbs;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ParamIndices extends Table {
  public static ParamIndices getRootAsParamIndices(ByteBuffer _bb) { return getRootAsParamIndices(_bb, new ParamIndices()); }
  public static ParamIndices getRootAsParamIndices(ByteBuffer _bb, ParamIndices obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ParamIndices __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int idxs(int j) { int o = __offset(4); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int idxsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer idxsAsByteBuffer() { return __vector_as_bytebuffer(4, 4); }
  public ByteBuffer idxsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 4); }

  public static int createParamIndices(FlatBufferBuilder builder,
      int idxsOffset) {
    builder.startObject(1);
    ParamIndices.addIdxs(builder, idxsOffset);
    return ParamIndices.endParamIndices(builder);
  }

  public static void startParamIndices(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addIdxs(FlatBufferBuilder builder, int idxsOffset) { builder.addOffset(0, idxsOffset, 0); }
  public static int createIdxsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startIdxsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endParamIndices(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // idxs
    return o;
  }
}

